# Generated by Django 5.0.6 on 2024-05-25 18:35

import django.core.validators
import django.utils.timezone
import loans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(error_messages={'blank': 'El campo DNI no puede estar vacío.', 'max_length': 'El DNI debe tener un máximo de 8 caracteres.'}, max_length=8, validators=[django.core.validators.RegexValidator(message='El DNI debe ser un número con un máximo de 8 dígitos.', regex='^\\d{1,8}$')])),
                ('full_name', models.CharField(error_messages={'blank': 'El campo Nombre y Apellido no puede estar vacío.'}, max_length=255)),
                ('gender', models.CharField(error_messages={'blank': 'El campo Género no puede estar vacío.'}, max_length=10)),
                ('email', models.EmailField(error_messages={'blank': 'El campo Email no puede estar vacío.', 'invalid': 'Por favor, introduce una dirección de correo electrónico válida.'}, max_length=254, validators=[django.core.validators.EmailValidator(message='Por favor, introduce una dirección de correo electrónico válida.')])),
                ('amount', models.DecimalField(decimal_places=2, error_messages={'blank': 'El campo Monto no puede estar vacío.', 'max_decimal_places': 'El monto solicitado no puede tener más de 2 decimales.'}, max_digits=9, validators=[loans.models.validate_amount])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
